//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nira_SampleProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_login
    {
        public decimal login_Id { get; set; }
        public string login_Name { get; set; }
        public string login_Email { get; set; }
        public string login_Password { get; set; }
        public bool login_IsActive { get; set; }
        public System.DateTime login_UpdatedDate { get; set; }
        public System.DateTime login_CreatedDate { get; set; }
    }
}
